### ISSUE TITLE
Unhelpful Comment / What does this function do

### ISSUE THREAD

**Issue by FAUSheppy** [beekama/NutritionApp#16]
https://github.com/beekama/NutritionApp/blob/1514ea6686dc3765551baaa2bb252c544a67e131/app/src/main/java/com/example/nutritionapp/other/Utils.java#L127

**Comment by FAUSheppy** [comment]
Are there maybe some resources missing/not commited?

When opening the Log, the function gets called with "TUESDAY" and return 0 (aka not found probably). This causes the app to crash:

Relevant parts of stacktrace:

    AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 24928
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getString(Resources.java:441)
        at android.content.Context.getString(Context.java:578)
        at com.example.nutritionapp.other.Utils.getDateFormattedHeader(Utils.java:136)
        at com.example.nutritionapp.foodJournal.overviewFoodsLists.FoodOverviewAdapter.onBindViewHolder(FoodOverviewAdapter.java:168)

**Comment by FAUSheppy** [comment]
https://github.com/beekama/NutritionApp/commit/03c8c3a88aff688ba8224cfa49ef7495fd4705b6
