### ISSUE TITLE
Adding Weight in Settings fails

### ISSUE THREAD

**Issue by FAUSheppy** [beekama/NutritionApp#17]
Adding a new weight entry fails if you:

- only have one entry
- delete this entry
- create a new entry without going back to settings first

This is because the recyler view reuses the existing ViewHolder and calls bindView instead of createView, which means the entryKey sets won't be updated with the new entry, meaning the List is empty and this happens:

    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.example.nutritionapp.WeightTrackingWeightListAdapter.onBindViewHolder(WeightTrackingWeightListAdapter.java:69)

**Comment by FAUSheppy** [comment]
And long story short: This is why one shouldn't create sub-variables for data-set entries, because if you then do this:

https://github.com/beekama/NutritionApp/blob/c29a8d313c17c3160c0d7c067c3bb2fabf7e6b6b/app/src/main/java/com/example/nutritionapp/WeightTracking.java#L199

It won't work :)

**Comment by FAUSheppy** [comment]
It's also unessesary to use a List for sorting at all, you can and  should use a sorted **Set** like **TreeSet**:

    TreeSet<String> set = new TreeSet<String>();
    set.add("B");
    set.add("A");
    set.add("C");
       
    for (String s : set) {
        System.out.println(s);
    }

*Output:*

    A
    B
    C

**Comment by FAUSheppy** [comment]
Fixed in: https://github.com/beekama/NutritionApp/commit/86d98a1873103cb2ca5b05cc0d24127285d0d578
